language: php
sudo: false
php:
  - 7.1
  - 7.4
jobs:
  include:
    - php: 7.4
      env: PREFER_LOWEST=""
      before_script:
        - &composerupdate
            composer update --no-interaction --no-progress --optimize-autoloader $PREFER_LOWEST
      script:
        - &phpunit
            "./vendor/bin/phpunit"
        - composer phpstan
        - composer cs-check
      after_script:
        - travis_retry php vendor/bin/php-coveralls -v
    - php: 7.1
      env: PREFER_LOWEST=""
      before_script:
        - *composerupdate
      script:
        - *phpunit
    - php: 7.1
      env: PREFER_LOWEST="--prefer-lowest"
      before_script:
        - *composerupdate
      script:
        - *phpunit

cache:
  directories:
  - "$HOME/.composer/cache"
after_success:
- vendor/bin/coveralls -v
